Loading config from /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/data/test_config.yaml ...
[38;21m2023-09-21 14:57:09,190 :: DEBUG :: icloudpy.base :: base.py :: 246 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2023-09-21 14:57:09,190 :: INFO :: icloudpy.base :: base.py :: 253 :: Session file does not exist[0m
[38;21m2023-09-21 14:57:09,191 :: DEBUG :: icloudpy.base :: base.py :: 318 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2023-09-21 14:57:09,192 :: DEBUG :: icloudpy.base :: base.py :: 350 :: Authentication completed successfully[0m
[38;5;39m2023-09-21 14:57:09,194 :: INFO :: root :: sync_drive.py :: 192 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Scanned document 1.pdf ...[0m
[38;21m2023-09-21 14:57:09,195 :: DEBUG :: root :: sync_drive.py :: 135 :: No changes detected. Skipping the file /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Scanned document 1.pdf ...[0m
[38;5;39m2023-09-21 14:57:09,195 :: INFO :: root :: sync_drive.py :: 192 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Scanned document 1.pdf ...[0m
