[38;21m2025-10-18 19:47:07,955 :: DEBUG :: icloudpy.base :: base.py :: 240 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2025-10-18 19:47:07,956 :: INFO :: icloudpy.base :: base.py :: 247 :: Session file does not exist[0m
[38;21m2025-10-18 19:47:07,956 :: DEBUG :: icloudpy.base :: base.py :: 313 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2025-10-18 19:47:07,965 :: DEBUG :: icloudpy.base :: base.py :: 417 :: Authentication completed successfully[0m
[38;5;226m2025-10-18 19:47:07,965 :: WARNING :: root :: photo_path_utils.py :: 50 :: Unknown filetype invalid for original_alt version of mock_filename.xed[0m
