Loading config from /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/data/test_config.yaml ...
[38;21m2023-08-29 17:27:10,860 :: DEBUG :: icloudpy.base :: base.py :: 246 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2023-08-29 17:27:10,861 :: INFO :: icloudpy.base :: base.py :: 253 :: Session file does not exist[0m
[38;21m2023-08-29 17:27:10,861 :: DEBUG :: icloudpy.base :: base.py :: 318 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2023-08-29 17:27:10,862 :: DEBUG :: icloudpy.base :: base.py :: 350 :: Authentication completed successfully[0m
[38;5;226m2023-08-29 17:27:10,863 :: WARNING :: root :: sync_photos.py :: 92 :: File size thumb not found on server. Skipping the photo /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/photos/filename__thumb__c29tZS1yYW5kb20taWQ=.JPG ...[0m
