Loading config from /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/data/test_config.yaml ...
[38;21m2022-04-13 21:43:50,411 :: DEBUG :: icloudpy.base :: base.py :: 242 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2022-04-13 21:43:50,412 :: INFO :: icloudpy.base :: base.py :: 249 :: Session file does not exist[0m
[38;21m2022-04-13 21:43:50,412 :: DEBUG :: icloudpy.base :: base.py :: 314 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2022-04-13 21:43:50,413 :: DEBUG :: icloudpy.base :: base.py :: 346 :: Authentication completed successfully[0m
[38;21m2022-04-13 21:43:50,415 :: DEBUG :: root :: config_parser.py :: 173 :: Checking drive destination ...[0m
[38;21m2022-04-13 21:43:50,416 :: DEBUG :: root :: config_parser.py :: 91 :: Checking root destination ...[0m
[38;21m2022-04-13 21:43:50,416 :: DEBUG :: root :: config_parser.py :: 200 :: Removing obsolete files and folders ...[0m
[38;21m2022-04-13 21:43:50,417 :: DEBUG :: root :: sync_drive.py :: 66 :: Skipping the unwanted folder /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Numbers ...[0m
[38;21m2022-04-13 21:43:50,418 :: DEBUG :: root :: sync_drive.py :: 66 :: Skipping the unwanted folder /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Pages ...[0m
[38;21m2022-04-13 21:43:50,419 :: DEBUG :: root :: sync_drive.py :: 66 :: Skipping the unwanted folder /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Preview ...[0m
[38;21m2022-04-13 21:43:50,420 :: DEBUG :: root :: sync_drive.py :: 91 :: File /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/icloudpy/Test/Document scanne 2.pdf does not exist locally.[0m
[38;5;39m2022-04-13 21:43:50,420 :: INFO :: root :: sync_drive.py :: 98 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/icloudpy/Test/Document scanne 2.pdf ...[0m
[38;21m2022-04-13 21:43:50,421 :: DEBUG :: root :: sync_drive.py :: 91 :: File /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/icloudpy/Test/Scanned document 1.pdf does not exist locally.[0m
[38;5;39m2022-04-13 21:43:50,421 :: INFO :: root :: sync_drive.py :: 98 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/icloudpy/Test/Scanned document 1.pdf ...[0m
[38;21m2022-04-13 21:43:50,423 :: DEBUG :: root :: sync_drive.py :: 66 :: Skipping the unwanted folder /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/unwanted ...[0m
[38;21m2022-04-13 21:43:50,424 :: DEBUG :: root :: sync_drive.py :: 91 :: File /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/This is a title.md does not exist locally.[0m
[38;5;39m2022-04-13 21:43:50,425 :: INFO :: root :: sync_drive.py :: 98 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/This is a title.md ...[0m
