[38;21m2025-10-21 00:53:04,574 :: DEBUG :: icloudpy.base :: base.py :: 240 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2025-10-21 00:53:04,575 :: INFO :: icloudpy.base :: base.py :: 247 :: Session file does not exist[0m
[38;21m2025-10-21 00:53:04,575 :: DEBUG :: icloudpy.base :: base.py :: 313 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2025-10-21 00:53:04,584 :: DEBUG :: icloudpy.base :: base.py :: 417 :: Authentication completed successfully[0m
