[38;21m2024-07-28 04:29:39,860 :: DEBUG :: icloudpy.base :: base.py :: 246 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2024-07-28 04:29:39,860 :: INFO :: icloudpy.base :: base.py :: 253 :: Session file does not exist[0m
[38;21m2024-07-28 04:29:39,860 :: DEBUG :: icloudpy.base :: base.py :: 318 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2024-07-28 04:29:39,861 :: DEBUG :: icloudpy.base :: base.py :: 350 :: Authentication completed successfully[0m
[38;21m2024-07-28 04:29:39,862 :: DEBUG :: root :: sync_drive.py :: 130 :: Package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/FotoksiÄ…Å¼ka-WzÃ³r.xmcf does not exist locally.[0m
[38;5;39m2024-07-28 04:29:39,862 :: INFO :: root :: sync_drive.py :: 203 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/FotoksiÄ…Å¼ka-WzÃ³r.xmcf ...[0m
[38;5;39m2024-07-28 04:29:39,863 :: INFO :: root :: sync_drive.py :: 166 :: Unpacking /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/FotoksiÄ…Å¼ka-WzÃ³r.xmcf.zip to /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive[0m
[38;5;39m2024-07-28 04:29:39,866 :: INFO :: root :: sync_drive.py :: 187 :: Successfully unpacked the package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/FotoksiÄ…Å¼ka-WzÃ³r.xmcf.zip.[0m
