[38;21m2025-10-25 17:03:02,269 :: DEBUG :: root :: config_logging.py :: 44 :: Checking root destination ...[0m
[38;21m2025-10-25 17:03:02,269 :: DEBUG :: root :: usage.py :: 40 :: Initialized usage cache at: /config/.data[0m
[38;5;226m2025-10-25 17:03:02,271 :: WARNING :: root :: usage.py :: 180 :: Request failed with status 503, attempt 1/3[0m
[38;21m2025-10-25 17:03:02,271 :: DEBUG :: root :: usage.py :: 195 :: Waiting 1.0s before retry...[0m
[38;5;226m2025-10-25 17:03:02,271 :: WARNING :: root :: usage.py :: 180 :: Request failed with status 503, attempt 2/3[0m
[38;21m2025-10-25 17:03:02,271 :: DEBUG :: root :: usage.py :: 195 :: Waiting 2.0s before retry...[0m
[38;21m2025-10-25 17:03:02,272 :: DEBUG :: root :: config_logging.py :: 44 :: Checking root destination ...[0m
[38;21m2025-10-25 17:03:02,272 :: DEBUG :: root :: usage.py :: 40 :: Initialized usage cache at: /config/.data[0m
