[38;21m2025-10-25 17:02:51,907 :: DEBUG :: icloudpy.base :: base.py :: 236 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2025-10-25 17:02:51,907 :: INFO :: icloudpy.base :: base.py :: 243 :: Session file does not exist[0m
[38;21m2025-10-25 17:02:51,908 :: DEBUG :: icloudpy.base :: base.py :: 308 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2025-10-25 17:02:51,916 :: DEBUG :: icloudpy.base :: base.py :: 412 :: Authentication completed successfully[0m
[38;21m2025-10-25 17:02:51,923 :: DEBUG :: root :: config_logging.py :: 44 :: Checking photos destination ...[0m
[38;21m2025-10-25 17:02:51,923 :: DEBUG :: root :: config_logging.py :: 44 :: Checking root destination ...[0m
[38;21m2025-10-25 17:02:51,924 :: DEBUG :: root :: config_logging.py :: 44 :: Checking photos destination ...[0m
[38;21m2025-10-25 17:02:51,924 :: DEBUG :: root :: config_logging.py :: 44 :: Checking root destination ...[0m
[38;5;39m2025-10-25 17:02:51,924 :: INFO :: root :: sync.py :: 257 :: Syncing photos...[0m
[38;5;39m2025-10-25 17:02:51,924 :: INFO :: root :: sync.py :: 259 :: Photos synced[0m
