[38;21m2025-10-28 05:09:04,047 :: DEBUG :: icloudpy.base :: base.py :: 236 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2025-10-28 05:09:04,047 :: INFO :: icloudpy.base :: base.py :: 243 :: Session file does not exist[0m
[38;21m2025-10-28 05:09:04,047 :: DEBUG :: icloudpy.base :: base.py :: 308 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2025-10-28 05:09:04,056 :: DEBUG :: icloudpy.base :: base.py :: 412 :: Authentication completed successfully[0m
[38;5;39m2025-10-28 05:09:04,057 :: INFO :: root :: drive_file_download.py :: 38 :: Downloading /home/runner/work/icloud-docker/icloud-docker/tests/temp/icloud/drive/non-existent-folder/Scanned document 1.pdf ...[0m
[38;5;196m2025-10-28 05:09:04,057 :: ERROR :: root :: drive_file_download.py :: 64 :: Failed to download /home/runner/work/icloud-docker/icloud-docker/tests/temp/icloud/drive/non-existent-folder/Scanned document 1.pdf: [Errno 2] No such file or directory: '/home/runner/work/icloud-docker/icloud-docker/tests/temp/icloud/drive/non-existent-folder/Scanned document 1.pdf'[0m
