Loading config from /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/data/test_config.yaml ...
[38;21m2023-01-09 23:13:21,209 :: DEBUG :: icloudpy.base :: base.py :: 246 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2023-01-09 23:13:21,209 :: INFO :: icloudpy.base :: base.py :: 253 :: Session file does not exist[0m
[38;21m2023-01-09 23:13:21,210 :: DEBUG :: icloudpy.base :: base.py :: 318 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2023-01-09 23:13:21,211 :: DEBUG :: icloudpy.base :: base.py :: 350 :: Authentication completed successfully[0m
[38;21m2023-01-09 23:13:21,213 :: DEBUG :: root :: sync_drive.py :: 132 :: File /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/icloudpy/Test/Document scanne 2.pdf does not exist locally.[0m
[38;5;39m2023-01-09 23:13:21,213 :: INFO :: root :: sync_drive.py :: 176 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/icloudpy/Test/Document scanne 2.pdf ...[0m
[38;21m2023-01-09 23:13:21,214 :: DEBUG :: root :: sync_drive.py :: 132 :: File /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/icloudpy/Test/Scanned document 1.pdf does not exist locally.[0m
[38;5;39m2023-01-09 23:13:21,214 :: INFO :: root :: sync_drive.py :: 176 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/icloudpy/Test/Scanned document 1.pdf ...[0m
[38;21m2023-01-09 23:13:21,215 :: DEBUG :: root :: sync_drive.py :: 132 :: File /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/This is a title.md does not exist locally.[0m
[38;5;39m2023-01-09 23:13:21,215 :: INFO :: root :: sync_drive.py :: 176 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/This is a title.md ...[0m
[38;21m2023-01-09 23:13:21,216 :: DEBUG :: root :: sync_drive.py :: 107 :: Package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/Project.band does not exist locally.[0m
[38;5;39m2023-01-09 23:13:21,217 :: INFO :: root :: sync_drive.py :: 176 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/Project.band ...[0m
[38;5;39m2023-01-09 23:13:21,218 :: INFO :: root :: sync_drive.py :: 143 :: Unpacking /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/Project.band.zip to /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample[0m
[38;5;39m2023-01-09 23:13:21,224 :: INFO :: root :: sync_drive.py :: 160 :: Successfully unpacked the package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/Project.band.zip.[0m
[38;21m2023-01-09 23:13:21,225 :: DEBUG :: root :: sync_drive.py :: 107 :: Package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band does not exist locally.[0m
[38;5;39m2023-01-09 23:13:21,225 :: INFO :: root :: sync_drive.py :: 176 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band ...[0m
[38;5;39m2023-01-09 23:13:21,228 :: INFO :: root :: sync_drive.py :: 149 :: Unpacking /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band.gz to /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample[0m
[38;5;39m2023-01-09 23:13:21,230 :: INFO :: root :: sync_drive.py :: 143 :: Unpacking /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band.zip to /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample[0m
[38;5;39m2023-01-09 23:13:21,235 :: INFO :: root :: sync_drive.py :: 160 :: Successfully unpacked the package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band.zip.[0m
[38;5;39m2023-01-09 23:13:21,235 :: INFO :: root :: sync_drive.py :: 160 :: Successfully unpacked the package /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band.gz.[0m
[38;5;196m2023-01-09 23:13:21,236 :: ERROR :: root :: sync_drive.py :: 186 :: Failed to download /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Obsidian/Sample/ms.band: [Errno 2] No such file or directory[0m
