[38;21m2024-07-28 18:07:37,732 :: DEBUG :: icloudpy.base :: base.py :: 246 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2024-07-28 18:07:37,732 :: INFO :: icloudpy.base :: base.py :: 253 :: Session file does not exist[0m
[38;21m2024-07-28 18:07:37,732 :: DEBUG :: icloudpy.base :: base.py :: 318 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2024-07-28 18:07:37,733 :: DEBUG :: icloudpy.base :: base.py :: 350 :: Authentication completed successfully[0m
[38;21m2024-07-28 18:07:37,734 :: DEBUG :: root :: sync_drive.py :: 34 :: Skipping the unwanted file /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/data/test_config.yaml[0m
