[38;21m2025-10-18 18:56:13,328 :: DEBUG :: icloudpy.base :: base.py :: 240 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2025-10-18 18:56:13,329 :: INFO :: icloudpy.base :: base.py :: 247 :: Session file does not exist[0m
[38;21m2025-10-18 18:56:13,329 :: DEBUG :: icloudpy.base :: base.py :: 313 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2025-10-18 18:56:13,338 :: DEBUG :: icloudpy.base :: base.py :: 417 :: Authentication completed successfully[0m
[38;21m2025-10-18 18:56:13,339 :: DEBUG :: root :: drive_parallel_download.py :: 99 :: [Thread] Starting download of /home/runner/work/icloud-docker/icloud-docker/tests/temp/icloud/drive/test_file.pdf[0m
[38;5;196m2025-10-18 18:56:13,340 :: ERROR :: root :: drive_parallel_download.py :: 118 :: [Thread] Failed to download /home/runner/work/icloud-docker/icloud-docker/tests/temp/icloud/drive/test_file.pdf: Test download error[0m
