[38;21m2025-10-18 17:17:09,666 :: DEBUG :: icloudpy.base :: base.py :: 240 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2025-10-18 17:17:09,667 :: INFO :: icloudpy.base :: base.py :: 247 :: Session file does not exist[0m
[38;21m2025-10-18 17:17:09,667 :: DEBUG :: icloudpy.base :: base.py :: 313 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2025-10-18 17:17:09,677 :: DEBUG :: icloudpy.base :: base.py :: 417 :: Authentication completed successfully[0m
[38;5;39m2025-10-18 17:17:09,678 :: INFO :: root :: drive_file_download.py :: 38 :: Downloading /home/runner/work/icloud-docker/icloud-docker/tests/temp/icloud/drive/Scanned document 1.pdf ...[0m
[38;21m2025-10-18 17:17:09,679 :: DEBUG :: root :: drive_file_existence.py :: 46 :: No changes detected. Skipping the file /home/runner/work/icloud-docker/icloud-docker/tests/temp/icloud/drive/Scanned document 1.pdf ...[0m
[38;21m2025-10-18 17:17:09,680 :: DEBUG :: root :: drive_file_existence.py :: 49 :: Changes detected: local_modified_time is 1760807829, remote_modified_time is 1588464917, local_file_size is 340532 and remote_file_size is 197334.[0m
[38;5;39m2025-10-18 17:17:09,680 :: INFO :: root :: drive_file_download.py :: 38 :: Downloading /home/runner/work/icloud-docker/icloud-docker/tests/temp/icloud/drive/Scanned document 1.pdf ...[0m
